server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:AUTH-SERVICE}

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql_db}:${DB_PORT:3306}/${DB_NAME:auth_db}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://localhost:3306/auth_db
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}

logging:
  level:
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:auth-service}
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}