server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:CART-SERVICE}

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql_db}:${DB_PORT:3306}/${DB_NAME:cart_db}
#    url: jdbc:mysql://localhost:3306/auth_db
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:cart-service}
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}