server:
  port: ${SERVER_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: RESTAURANT-SERVICE

  kafka:
    # Connects to 'kafka:29092' inside Docker
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
    template:
      default-topic: ${KAFKA_TOPIC:notification-topic}

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql_db}:${DB_PORT:3306}/${DB_NAME:restaurant_db}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://elasticsearch:9200}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL}